### ISSUE TITLE
Showing gibberish in Windows terminal

### ISSUE THREAD

**Issue by tsehori** [elad661/curlbus#18]
Trying to curl through Windows cmd gives the following screen:
<img width="630" alt="capture" src="https://user-images.githubusercontent.com/10086302/44365435-794d5a00-a4d2-11e8-844b-9350519d4f0d.PNG">
I'm not sure if this issue is on my end or in the code. I would like some input on that, if possible.

The HTML-based terminal-like UI works well.
Hebrew installed on the computer. Tested on Windows 10 Home.

**Comment by elad661** [comment]
I think I can say Windows is not officially supported.

There are two issues here:
1. Your terminal seems to be not configured for Unicode. I don't know if it's possible to configure the Windows terminal to properly display unicode text, but if it is - you should try that.
2. Your terminal does not know how to handle ANSI color escape codes. I thought one of the recent big Windows 10 updates added support for that, but maybe they didn't - I don't know.

curlbus uses unicode and ansi color codes all over the place, so I can't just remove them. It's mainly built for people who use Linux or Mac, because people who use Windows don't usually have curl :)

If you want to use curlbus via curl on windows, you might need a better terminal emulator instead of cmd.exe

Out of curiosity, which Windows 10 build are you running? you can find out by running `winver.exe`

Closing this issue, as there's nothing I can do to fix it on my end.

**Comment by tsehori** [comment]
Thanks for replying so quickly! I tried playing around a bit with Windows command line and also the PowerShell, with no much success.
I'm running version 1803 os build 17134.165. Will try a different terminal emulator. Thanks!
