### ISSUE TITLE
When provide "111" as a "stop_code" the server returns status code 500

### ISSUE THREAD

**Issue by denpy** [elad661/curlbus#24]
**How to reproduce:**
Use "111" as the stop code, for example run `curl https://curlbus.app/111` in terminal

**Expected result:**
Either status code 200 OK or 404 Not found.

**Current result:**
Status code 500  Internal Server Error.

**Comment by elad661** [comment]
weird, it works for me. I'll look at the logs later.

**Comment by denpy** [comment]
Indeed, it's weird because now it works for me too.
Here is some additional data, maybe the exact time will be helpful.
```
http https://curlbus.app/111

HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 55
Content-Type: text/plain; charset=utf-8
Date: Mon, 22 Jun 2020 12:08:10 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

500 Internal Server Error

Server got itself in trouble
```

**Comment by elad661** [comment]
I looked at the logs for this timestamp. looks like occasionally the MoT API server is returning incorrectly encoded content since the traceback seems like an decoding error in Python's `cp1252.py`, the decoder for Windows-1252

I assume that either they're returning a bad content encoding header, or that aiohttp tries to guess the encoding and fail. Happening only occasionally means that it might be an issue with one of their backend server, and not the other. Fun.

I can't do much to get the MoT to fix their software, and in Israel it seems like a general rule that the government can never get text encoding right :) but I can try to fix curlbus to handle this kind of error, and produce a more meaningful error message.

hopefully I'll have time to investigate this further sometime this week.

**Comment by denpy** [comment]
Cool, thanks! 😊

**Comment by elad661** [comment]
Should be fixed now! let me know if it happens again.

**Comment by denpy** [comment]
Sure, no problem 👍🏾
